name: terminal-tunnel
base: core24
adopt-info: terminal-tunnel
summary: P2P terminal sharing with E2E encryption
description: |
  Terminal Tunnel enables secure, peer-to-peer terminal sharing.
  Share your terminal with anyone via a web browser with end-to-end encryption.

  Features:
  - End-to-end encryption with password protection
  - No account required - just share the code
  - Works through NAT with WebRTC
  - Web-based viewer - no client installation needed
  - Session recording and playback

  Usage:
    tt daemon start      # Start the daemon
    tt start -p mysecret # Start a session
    tt list              # List all sessions
    tt stop <code>       # Stop a session

grade: stable
confinement: classic

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

apps:
  tt:
    command: bin/tt
    plugs:
      - network
      - network-bind
      - home

parts:
  terminal-tunnel:
    plugin: go
    source: .
    source-type: local
    build-snaps:
      - go/1.24/stable
    build-environment:
      - CGO_ENABLED: "0"
    override-build: |
      VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
      COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
      DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)

      go build -ldflags="-s -w -X main.version=${VERSION} -X main.commit=${COMMIT} -X main.date=${DATE}" \
        -o $SNAPCRAFT_PART_INSTALL/bin/tt ./cmd/terminal-tunnel

      craftctl set version="${VERSION#v}"
    override-pull: |
      craftctl default
      git fetch --tags --force
